### ISSUE TITLE
Upgrade cson-parser dependency when their Issue #67 is resolved

### ISSUE THREAD

**Issue by notmessenger** [outaTiME/applause#11]
Once https://github.com/groupon/cson-parser/issues/67 is resolved this repo's dependency on the `cson-parser` dependency should be upgraded to address the

> coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)

deprecation.

**Comment by poplevente** [comment]
would be nice to get that package update

**Comment by outaTiME** [comment]
The new version of Applause is released:

https://github.com/outaTiME/applause/releases/tag/2.0.0
