### ISSUE TITLE
1 low severity vulnerability

### ISSUE THREAD

**Issue by philwareham** [outaTiME/applause#14]
`npm audit` shows that `applause > lodash` dependency has a vulnerability that was fixed in a later release of lodash. Can you update dependency requirement to fix that. Primarily because I use your grunt-replace plugin which relies on applause. Cheers!

**Comment by gbochenek** [comment]
I created and published a fork to update security vulnerabilities:

https://github.com/gbochenek/next-applause

**Comment by outaTiME** [comment]
The new version of Applause is released:

https://github.com/outaTiME/applause/releases/tag/2.0.0
