### ISSUE TITLE
Update lodash dependency 

### ISSUE THREAD

**Issue by mikecbrant** [outaTiME/applause#15]
There is previous issue noted at https://github.com/outaTiME/applause/issues/14 to update lodash for a low severity vulnerability.

I am opening this issue (which requires same solution as the issue noted above) to note that npm is now reporting a moderate severity issue in the version of lodash being  used.  Hopefully that will give some higher priority to this issue.

**Comment by noahcooper** [comment]
There is now a high severity vulnerability in the old version of lodash being used.

**Comment by outaTiME** [comment]
The new version of Applause is released:

https://github.com/outaTiME/applause/releases/tag/2.0.0
