### ISSUE TITLE
BUG: TypeError: content.match is not a function

### ISSUE THREAD

**Issue by MrJithil** [outaTiME/applause#20]
While using applause for replacements, we are getting below errors.
```
TypeError: content.match is not a function
    at d:\OpenSource\nodejs.org\node_modules\applause\src\applause.js:159:26
    at Array.forEach (<anonymous>:null:null)
    at Applause.replace (d:\OpenSource\nodejs.org\node_modules\applause\src\applause.js:106:12)
    at d:\OpenSource\nodejs.org\node_modules\metalsmith-replace\lib\replace.js:24:43
    at Array.forEach (<anonymous>:null:null)
    at d:\OpenSource\nodejs.org\node_modules\metalsmith-replace\lib\replace.js:16:34
    at Array.forEach (<anonymous>:null:null)
    at Ware.<anonymous> (d:\OpenSource\nodejs.org\node_modules\metalsmith-replace\lib\replace.js:14:28)
    at Ware.<anonymous> (d:\OpenSource\nodejs.org\node_modules\wrap-fn\index.js:45:19)
    at next (d:\OpenSource\nodejs.org\node_modules\ware\lib\index.js:85:20)
    at d:\OpenSource\nodejs.org\node_modules\wrap-fn\index.js:121:18
    at d:\OpenSource\nodejs.org\node_modules\metalsmith-layouts\lib\index.js:141:17
    at runMicrotasks (<anonymous>:null:null)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

This error is being shown while using the `metalsmith-replace` which uses `applause` internally.

**Comment by outaTiME** [comment]
Hi @MrJithil, 
great one, but `replace` a method only accepts string as a parameter, what kind of data type are you passing? I actually handling `falsy` contents as well to prevent issues like you see in the following line:

https://github.com/outaTiME/applause/blob/master/src/applause.js#L96

**Comment by MrJithil** [comment]
@outaTiME There are chances to accept numeric endpoints like 404.

I was building a repository where the metalsmith and replace being used. There I faced this issue. After the fix, everything worked well.

**Comment by outaTiME** [comment]
I understand, but I think the best thing to do would be to filter the content that is not a string to avoid the call to `replace`, it does not make sense to call it with some type of data that is not a string, it is probably an error of `metalsmith` rather than of `applause`.

I think the best thing would be to `applause` throw an error if it receives any data that is not of the string type, in your PR you detect the data type and return a valid replacement result, and probably this should not.

Could you share some of your code with me to see if we can make any adjustments there? or is the problem from metalsmith?

**Comment by MrJithil** [comment]
@outaTiME, we have workarounds in pitch already.
`metalsmith-replace` is not only sending strings. We can not guaranty that since all the titles are valid. If a title only contains non-string data type values like `404md`, `true.md` , JavaScript inference it to the `number` and `boolean` datatype. So, we cannot state that replace should only send a string to `applause`.

You may replicate the same by creating a repo with numeric names.

The code here trying to use the `match`  function without type-check or typecasting is definitely an issue of this repo in my perspective.

**Comment by outaTiME** [comment]
ok i understand, but i still think that `metalsmith-replace` should convert the datatype it receives to a string

however I am going to accept your workaround PR like this and add some test cases,

thanks for your contribution !!!

**Comment by MrJithil** [comment]
Thanks, @outaTiME , I will work on that repo and identify that. I will definitely add you there for a review.
