### ISSUE TITLE
Question: why "@@" as a default prefix?

### ISSUE THREAD

**Issue by machty** [outaTiME/applause#4]
Why "@@"? Is that specific to some language/markup? Why would it be a default value of prefix over just an empty string?

**Comment by outaTiME** [comment]
Hi pal, 

I dont know the default was taken from grunt-replace plugin our users use that default here in applause we can change that to use empty prefix … what do you think ?

**Comment by outaTiME** [comment]
Pal, feedback will be welcome ...

**Comment by outaTiME** [comment]
No feedback, closing for now ...
