### ISSUE TITLE
json replace is a bit funny with similar property names

### ISSUE THREAD

**Issue by oliverfoster** [outaTiME/applause#9]
### This kind of config:
```json
{
  "json": {
    "test1": {
        "property1": "value1",
        "property1_name": "value2",
    }
  }
```
### With this text:
``some text to replace with @@property1_name here``

### Will become
``some text to replace with value1_name here``

### Not
``some text to replace with value2 here``

Can i suggest you reverse sort the property names in the flatten function? 
That way larger (longer) names will be processed first and this problem goes away.

**Comment by outaTiME** [comment]
Hi @oliverfoster, you could solve this escenario? why close the issue?

**Comment by oliverfoster** [comment]
https://github.com/outaTiME/applause/blob/master/src/applause.js#L70 < i was jumping to conclusions, the library handles itself just fine :+1: 
thanks for asking

**Comment by outaTiME** [comment]
Great, np, if you need something let me know, thanks for using applause 👏 👏 👏

**Comment by oliverfoster** [comment]
cool, good to know 👍
